START TRANSACTION;
DROP TABLE IF EXISTS `fund`;
DROP TABLE IF EXISTS `fund_nav`;
CREATE TABLE IF NOT EXISTS `fund` (
    `id` BIGINT AUTO_INCREMENT,
    `name` VARCHAR(100) NOT NULL,
    `code` VARCHAR(10) NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    `deleted_at` TIMESTAMP,
    PRIMARY KEY(`id`),
    INDEX `idx_code` (`code`)
);
CREATE TABLE IF NOT EXISTS `fund_nav` (
    `id` BIGINT AUTO_INCREMENT,
    `fund_id` BIGINT NOT NULL,
    `date` TIMESTAMP NOT NULL,
    `nav` DOUBLE NOT NULL,
    `cnav` DOUBLE NOT NULL,
    `growth` DOUBLE NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    `deleted_at` TIMESTAMP,
    PRIMARY KEY(`id`),
    UNIQUE INDEX `idx_fund_date` (`fund_id`, `date`)
);
COMMIT;