services:
  repository:
    image: fundation/repository:v0.1
    container_name: repository
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=mysql://root:000000@db:3306/fundation?parseTime=True
    depends_on:
      - db
    restart: always
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=000000
      - MYSQL_DATABASE=fundation
    restart: always
    volumes:
      - /root/project/fundation/.data:/var/lib/mysql
      - /root/project/fundation/.database:/docker-entrypoint-initdb.d
