POST http://localhost:8080/fund
content-type: application/json

{
    "name": "",
    "code": "004854"
}

###

POST http://localhost:8080/nav
content-type: application/json

{
    "data": [
        {
            "fund_id": 1,
            "date": 1719981505,
            "nav": 1.069,
            "cnav": 1.514,
            "growth": -3.69
        }
    ]
}

###
GET http://localhost:8080/nav?code=017437

###
GET http://localhost:8080/fund?code=017437

###
POST http://localhost:8080/stat
content-type: application/json

{
    "month": [1, 2, 3, 6, 12, 24, 36],
    "code": ["017437", "004243", "012348", "020111", "007301", "004854"]
}

###
GET http://localhost:8080/fund/list

###
GET http://localhost:8080/nav/latest?code=017437